/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package nvisao;

import controle.ConectaBanco;
import controle.ControleLocadora;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.io.InputStream;
import java.net.URL;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.AbstractAction;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;
import javax.swing.ListSelectionModel;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;
import modelo.ModeloLocaDvd;
import modelo.ModeloLocadora;
import modelo.ModeloTabela;

/**
 *
 * @author Delfino
 */
public class FrmLocadora extends javax.swing.JFrame {

    ConectaBanco conex = new ConectaBanco();
    ControleLocadora control = new ControleLocadora();
    ModeloLocadora mod = new ModeloLocadora();
    ModeloLocaDvd md = new ModeloLocaDvd();
    int codVenda;
    float total;
    int t=0;
    
     
    public FrmLocadora() {
        initComponents();
        
        URL url = this.getClass().getResource("/Imagens/dvd.png");  //coloca a imagem no lugar da tigela java
          Image imagemTitulo = Toolkit.getDefaultToolkit().getImage(url);  
            this.setIconImage(imagemTitulo);
        
        SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");
        Date hoje = new Date();
        DataInicio.setText(df.format(hoje));
        
        
        try {
            MaskFormatter form = new MaskFormatter("##/##/####");
            DataDevolu.setFormatterFactory(new DefaultFormatterFactory(form));
            
            
        } catch (ParseException ex) {
            Logger.getLogger(FrmCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
          ////////////////////////////////////////////////////////////////////////////////    
        //faz os botões serem acionados com a tecla enter
    AbstractAction action = new AbstractAction() {
    @Override
    public void actionPerformed(ActionEvent e) {
        if(e.getSource() instanceof JButton){
        JButton button = (JButton) e.getSource();
        button.doClick();        
        } else if(e.getSource() instanceof JComponent){
            JComponent component = (JComponent) e.getSource();
            component.transferFocus();
        }
    }
    };
    jButonAdicionarFilmes.getInputMap().put(KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0), "DoClick");
    jButonAdicionarFilmes.getActionMap().put("DoClick", action);
    jButtonIniciarGerarCodigo.getInputMap().put(KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0), "DoClick");
    jButtonIniciarGerarCodigo.getActionMap().put("DoClick", action);
    jButtonPesquisarDvd.getInputMap().put(KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0), "DoClick");
    jButtonPesquisarDvd.getActionMap().put("DoClick", action);
    jButton3.getInputMap().put(KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0), "DoClick");
    jButton3.getActionMap().put("DoClick", action);      
    jButton4.getInputMap().put(KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0), "DoClick");
    jButton4.getActionMap().put("DoClick", action);    
       // getRootPane().setDefaultButton(jButton8);//botão sair com enter
  ///////////////////////////////////////////////////////////////////////////////////////////////  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldCodCli = new javax.swing.JTextField();
        jTextFieldFilme = new javax.swing.JTextField();
        jTextFieldPre = new javax.swing.JTextField();
        jButtonIniciarGerarCodigo = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jButton3 = new javax.swing.JButton();
        DataInicio = new javax.swing.JFormattedTextField();
        DataDevolu = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableP = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableD = new javax.swing.JTable();
        jButonAdicionarFilmes = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLaCli = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jlaCodFilme = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButtonPesquisarDvd = new javax.swing.JButton();
        jLabelImagem = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelEst = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Locação");

        jLabel2.setText("Codigo do cliente:");

        jLabel4.setText("Preço:");

        jLabel5.setText("Data inicio:");

        jLabel6.setText("Data devolução:");

        jLabel8.setText("Tipo de pagamento:");

        jTextFieldCodCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCodCliActionPerformed(evt);
            }
        });

        jTextFieldFilme.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldFilme.setForeground(new java.awt.Color(0, 0, 255));
        jTextFieldFilme.setEnabled(false);
        jTextFieldFilme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFilmeActionPerformed(evt);
            }
        });

        jTextFieldPre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPreActionPerformed(evt);
            }
        });

        jButtonIniciarGerarCodigo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonIniciarGerarCodigo.setForeground(new java.awt.Color(255, 0, 0));
        jButtonIniciarGerarCodigo.setText("iniciar");
        jButtonIniciarGerarCodigo.setToolTipText("Gera o codigo de locação");
        jButtonIniciarGerarCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIniciarGerarCodigoActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Avista", "Devolução", " " }));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/search.png"))); // NOI18N
        jButton3.setToolTipText("Pesquisar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        DataInicio.setBackground(new java.awt.Color(0, 0, 0));
        DataInicio.setForeground(new java.awt.Color(255, 255, 0));
        DataInicio.setEnabled(false);
        DataInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DataInicioActionPerformed(evt);
            }
        });

        tableP.setBackground(new java.awt.Color(204, 255, 255));
        tableP.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tableP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tableP.setRowHeight(30);
        tableP.setRowMargin(15);
        tableP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablePMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableP);

        tableD.setBackground(new java.awt.Color(255, 204, 255));
        tableD.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        tableD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tableD.setRowHeight(30);
        jScrollPane2.setViewportView(tableD);

        jButonAdicionarFilmes.setText("Adicinoar");
        jButonAdicionarFilmes.setToolTipText("Adicionar");
        jButonAdicionarFilmes.setEnabled(false);
        jButonAdicionarFilmes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButonAdicionarFilmesActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLaCli.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLaCli.setForeground(new java.awt.Color(0, 0, 204));
        jLaCli.setText("-------------------");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 0, 153));
        jLabel9.setText("Adicionar filmes para : ");

        jButton4.setText("Finalizar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(69, 69, 69)
                .addComponent(jLaCli)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 137, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLaCli)
                    .addComponent(jButton4)))
        );

        jLabel1.setText("Codigo:");

        jlaCodFilme.setBackground(new java.awt.Color(51, 153, 0));
        jlaCodFilme.setForeground(new java.awt.Color(0, 153, 51));
        jlaCodFilme.setText("......");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 0));
        jLabel10.setText("Cliente:");

        jButtonPesquisarDvd.setText("Filme");
        jButtonPesquisarDvd.setToolTipText("Pesquisar nome do Filme");
        jButtonPesquisarDvd.setEnabled(false);
        jButtonPesquisarDvd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarDvdActionPerformed(evt);
            }
        });

        jLabelImagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/sugel.jpg"))); // NOI18N
        jLabelImagem.setText("DVD");

        jLabel3.setText("Quantidade:");

        jLabelEst.setBackground(new java.awt.Color(255, 51, 51));
        jLabelEst.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelEst.setForeground(new java.awt.Color(255, 51, 51));
        jLabelEst.setText("......");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldPre, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(DataDevolu, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(DataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(472, 472, 472))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jTextFieldCodCli, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(39, 39, 39)
                                        .addComponent(jButton3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButtonIniciarGerarCodigo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jlaCodFilme)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelEst))
                            .addComponent(jLabelImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButonAdicionarFilmes))
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(299, 299, 299)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextFieldFilme, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonPesquisarDvd))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(7, 7, 7)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel2)
                                            .addComponent(jTextFieldCodCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButton3))
                                        .addGap(40, 40, 40)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(DataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel6)
                                            .addComponent(DataDevolu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(28, 28, 28)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel8)
                                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel4)
                                            .addComponent(jTextFieldPre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jButtonIniciarGerarCodigo))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButonAdicionarFilmes, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelImagem)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(jlaCodFilme)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabelEst))
                                .addGap(68, 68, 68)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldFilme, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonPesquisarDvd))
                                .addGap(0, 37, Short.MAX_VALUE)))
                        .addGap(27, 27, 27)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(108, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldFilmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFilmeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFilmeActionPerformed

    private void jTextFieldCodCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCodCliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCodCliActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        conex.conexao();
        
        conex.execultasql("select * from clientes where id_cli='"+jTextFieldCodCli.getText()+"'");
        try {
            conex.rs.first();
            
            jLaCli.setText(conex.rs.getString("nome_cl"));
           
        } catch (SQLException ex) {
            Logger.getLogger(FrmLocadora.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButtonIniciarGerarCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIniciarGerarCodigoActionPerformed
         conex.conexao();
         
         
        try {
            PreparedStatement pst = conex.conn.prepareStatement("insert into locadora(preco)values(?)");
            pst.setFloat(1,0);// essas linhas são importantes para incrementar o codigo da locação
            pst.execute();
            
            
            conex.execultasql("select * from locadora ");
            conex.rs.last();
             codVenda=conex.rs.getInt("id_loca");
        } catch (SQLException ex) {
             JOptionPane.showMessageDialog(rootPane,"Erro:"+ex);
        }
           
         jTextFieldFilme.setEnabled(true);
         jButtonPesquisarDvd.setEnabled(true);
         jButonAdicionarFilmes.setEnabled(true);
         jButtonIniciarGerarCodigo.setEnabled(!true);
        
        
    }//GEN-LAST:event_jButtonIniciarGerarCodigoActionPerformed

    private void tablePMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePMouseClicked
        // TODO add your handling code here:
        
        String codD = ""+tableP.getValueAt(tableP.getSelectedRow(),0);
        jlaCodFilme.setText(codD);
        
       
        
        String titulo = ""+tableP.getValueAt(tableP.getSelectedRow(),1);
        jTextFieldFilme.setText(titulo);
        
        
        
         conex.conexao();
         
         ImageIcon foto;
            InputStream is ;
           
         
        try {         
                
                     
             conex.execultasql("select img,titulo,quantidade,tipo,id_dvd from dvds where titulo like  '%"+jTextFieldFilme.getText()+"%'");
            
            
            
            
            while(conex.rs.next()){                
           
         
                 
               is=conex.rs.getBinaryStream(1);
               
               
                BufferedImage bi = ImageIO.read(is);  
                
                 
                foto= new ImageIcon(bi);
                
                Image img=foto.getImage();
                
                Image newimg=img.getScaledInstance(200,200,java.awt.Image.SCALE_SMOOTH);
                
                ImageIcon newicon=new ImageIcon(newimg);
                
                jLabelImagem.setIcon(newicon);
                
            }   
            
             } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane,"Erro ao buscar a imagem!"+ex);
        }
        
        
        
        String s="select * from dvds where titulo like '%"+jTextFieldFilme.getText()+"%'";
              conex.execultasql(s);
        try {
            conex.rs.first();
            
            jLabelEst.setText(String.valueOf(conex.rs.getInt("quantidade")));
        } catch (SQLException ex) {
            Logger.getLogger(FrmLocadora.class.getName()).log(Level.SEVERE, null, ex);
        }
              
         
    }//GEN-LAST:event_tablePMouseClicked

    private void DataInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DataInicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DataInicioActionPerformed

    private void jButonAdicionarFilmesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButonAdicionarFilmesActionPerformed
                mod.setCodLoca(codVenda);
                mod.setCodDvd(Integer.parseInt(jlaCodFilme.getText()));
               // mod.setQuantidade(Integer.parseInt(jTextFieldQuant.getText()));
                mod.setPreco(Float.parseFloat(jTextFieldPre.getText()));
                mod.setTipoPag((String)jComboBox1.getSelectedItem());
                control.AdicionaFilmes(mod);
                //para preencher a tabela ao adicionar os filmes relacionando com o codigo do aluguel 
                preencherTabela("select * from locadora inner join loca_dvd on locadora.id_loca=loca_dvd.id_loca inner join dvds on loca_dvd.id_dvd=dvds.id_dvd where locadora.id_loca="+codVenda);
                 
                int r=0,quantidade=1,diminuir;
         conex.conexao();
        
         try {
              
                
              /////////////////////////////////////////////////////////    
                  
                 
                
               String sql="select * from dvds where titulo='"+jTextFieldFilme.getText()+"'";
             
                    conex.execultasql(sql);
                    
                    conex.rs.first();
                     diminuir=conex.rs.getInt("quantidade");
                      //quantidade=Integer.parseInt(jTextFieldQuant.getText());                 
                       
                       r=diminuir-quantidade;
                  
                   
                    
                     String at="update dvds set quantidade=? where titulo=?";
                
                  
                    PreparedStatement pst=conex.conn.prepareStatement(at);
                                       
                    pst.setInt(1,r);
                    pst.setString(2,jTextFieldFilme.getText());
                    pst.execute();
                    pst.close();
                    
                  //JOptionPane.showMessageDialog(rootPane,"Atualizado!");
                 } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(rootPane,"Erro!"+ ex);
                    conex.desconecta();
                }
             ///////////////////////////////////////////////////
         
         
          String s="select * from dvds where titulo= '"+jTextFieldFilme.getText()+"'";
              conex.execultasql(s);
        try {
            conex.rs.first();
            
            jLabelEst.setText(String.valueOf(conex.rs.getInt("quantidade")));
        } catch (SQLException ex) {
            Logger.getLogger(FrmLocadora.class.getName()).log(Level.SEVERE, null, ex);
        }
           
                   
       
    }//GEN-LAST:event_jButonAdicionarFilmesActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
       // mod.setQuantidade(Integer.parseInt(jTextFieldQuant.getText()));
        mod.setCodLoca(codVenda);
        mod.setDataInicio(DataInicio.getText());
        mod.setDataDevol(DataDevolu.getText());
       // mod.setTipoPag((String)jComboBox1.getSelectedItem());
        mod.setPreco(Float.parseFloat(jTextFieldPre.getText()));
        mod.setCoCl(Integer.parseInt(jTextFieldCodCli.getText()));
        mod.setNomeCl(jLaCli.getText());   
       // mod.setFime(jTextFieldFilme.getText());
        
        
        control.FechaLoca(mod);
        
        dispose();
        new FrmPesqDvd().setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextFieldPreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPreActionPerformed

    private void jButtonPesquisarDvdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarDvdActionPerformed
        // TODO add your handling code here:
         preencherTabela1("select * from dvds where titulo like'%"+jTextFieldFilme.getText()+"%'");
         conex.conexao();
         
         ImageIcon foto;
            InputStream is ;
           
         
        try {         
                
                     
             conex.execultasql("select img,titulo,quantidade,tipo,id_dvd from dvds where titulo like  '%"+jTextFieldFilme.getText()+"%'");
            
            
            
            
            while(conex.rs.next()){                
           
         
                 
               is=conex.rs.getBinaryStream(1);
               
               
                BufferedImage bi = ImageIO.read(is);  
                
                 
                foto= new ImageIcon(bi);
                
                Image img=foto.getImage();
                
                Image newimg=img.getScaledInstance(200,200,java.awt.Image.SCALE_SMOOTH);
                
                ImageIcon newicon=new ImageIcon(newimg);
                
                jLabelImagem.setIcon(newicon);
                
            }   
            
             } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane,"Erro ao buscar a imagem!"+ex);
        }

         
    }//GEN-LAST:event_jButtonPesquisarDvdActionPerformed

      public void preencherTabela(String sql){
        ArrayList dados = new ArrayList();
        String[] Colunas = new String[]{"Titulo","Tipo"};
       
    // String hora = Hora.getText();// Coloca a hora na tabela
        
        conex.conexao();
        conex.execultasql(sql);                
            try {
                conex.rs.first();
                do {
                  
                    dados.add(new Object[]{conex.rs.getString("titulo"),conex.rs.getString("tipo")});
                    
                      
                     
                   
                }while(conex.rs.next());
            } catch (SQLException ex) {
               // JOptionPane.showMessageDialog(rootPane,"Erro ao preencher o ArrayList!\nErro:"+ex);
            }
       
            
        ModeloTabela modelo = new ModeloTabela(dados, Colunas);
          tableD.setModel(modelo);
          tableD.getColumnModel().getColumn(0).setPreferredWidth(200);
          tableD.getColumnModel().getColumn(0).setResizable(false);
          tableD.getColumnModel().getColumn(1).setPreferredWidth(250);
          tableD.getColumnModel().getColumn(1).setResizable(false);  
          
          //tableD.getColumnModel().getColumn(3).setPreferredWidth(250);
          //tableD.getColumnModel().getColumn(3).setResizable(false);  
         /* jTable1.getColumnModel().getColumn(4).setPreferredWidth(80);
          jTable1.getColumnModel().getColumn(4).setResizable(false); 
          jTable1.getColumnModel().getColumn(5).setPreferredWidth(50);
          jTable1.getColumnModel().getColumn(5).setResizable(false); */  
          tableD.getTableHeader().setReorderingAllowed(false);
          tableD.setAutoResizeMode(tableD.AUTO_RESIZE_OFF);
          tableD.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);                                
    
       
       }
      
            public void preencherTabela1(String sql){
        ArrayList dados = new ArrayList();
        String[] Colunas = new String[]{"Codigo","Titulo","Tipo"};
       
    // String hora = Hora.getText();// Coloca a hora na tabela
        
        conex.conexao();
        conex.execultasql(sql);                
            try {
                conex.rs.first();
                do {
                  
                    dados.add(new Object[]{conex.rs.getString("id_dvd"),conex.rs.getString("titulo"),conex.rs.getString("tipo")});
                    
                   // j++;
                   
                   
                }while(conex.rs.next());
            } catch (SQLException ex) {
               // JOptionPane.showMessageDialog(rootPane,"Erro ao preencher o ArrayList!\nErro:"+ex);
            }
       
            
        ModeloTabela modelo = new ModeloTabela(dados, Colunas);
          tableP.setModel(modelo);
          tableP.getColumnModel().getColumn(0).setPreferredWidth(100);
          tableP.getColumnModel().getColumn(0).setResizable(false);
          tableP.getColumnModel().getColumn(1).setPreferredWidth(100);
          tableP.getColumnModel().getColumn(1).setResizable(false);  
          tableP.getColumnModel().getColumn(2).setPreferredWidth(100);
          tableP.getColumnModel().getColumn(2).setResizable(false);  
         /* jTable1.getColumnModel().getColumn(3).setPreferredWidth(60);
          jTable1.getColumnModel().getColumn(3).setResizable(false);  
          jTable1.getColumnModel().getColumn(4).setPreferredWidth(80);
          jTable1.getColumnModel().getColumn(4).setResizable(false); 
          jTable1.getColumnModel().getColumn(5).setPreferredWidth(50);
          jTable1.getColumnModel().getColumn(5).setResizable(false); */  
          tableP.getTableHeader().setReorderingAllowed(false);
          tableP.setAutoResizeMode(tableP.AUTO_RESIZE_OFF);
          tableP.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);                                
    
       
       }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmLocadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmLocadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmLocadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmLocadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmLocadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField DataDevolu;
    private javax.swing.JFormattedTextField DataInicio;
    private javax.swing.JButton jButonAdicionarFilmes;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButtonIniciarGerarCodigo;
    private javax.swing.JButton jButtonPesquisarDvd;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLaCli;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelEst;
    private javax.swing.JLabel jLabelImagem;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextFieldCodCli;
    private javax.swing.JTextField jTextFieldFilme;
    private javax.swing.JTextField jTextFieldPre;
    private javax.swing.JLabel jlaCodFilme;
    private javax.swing.JTable tableD;
    private javax.swing.JTable tableP;
    // End of variables declaration//GEN-END:variables
}
